// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

mistakesplit1.wad
mistakesplit10.wad
mistakesplit11.wad
mistakesplit12.wad
mistakesplit2.wad
mistakesplit3.wad
mistakesplit4.wad
mistakesplit5.wad
mistakesplit6.wad
mistakesplit7.wad
mistakesplit8.wad
mistakesplit9.wad
models/sence/mistake_coop/anita.mdl
models/sence/mistake_coop/anita22.mdl
models/sence/mistake_coop/bullsquid.mdl
models/sence/mistake_coop/coat_rack.mdl
models/sence/mistake_coop/doglott.mdl
models/sence/mistake_coop/flaska1.mdl
models/sence/mistake_coop/flaska2.mdl
models/sence/mistake_coop/flaska3.mdl
models/sence/mistake_coop/flaska4.mdl
models/sence/mistake_coop/gurulo.mdl
models/sence/mistake_coop/headcrab.mdl
models/sence/mistake_coop/kulcs1.mdl
models/sence/mistake_coop/lakat.mdl
models/sence/mistake_coop/lampa.mdl
models/sence/mistake_coop/papir3.mdl
models/sence/mistake_coop/szek2.mdl
models/sence/mistake_coop/szek3.mdl
models/sence/mistake_coop/virag.mdl
models/sence/mistake_coop/w_suit.mdl
models/sence/mistake_coop/weapons/mp5_shell.mdl
models/sence/mistake_coop/weapons/p_aps.mdl
models/sence/mistake_coop/weapons/p_crowbar.mdl
models/sence/mistake_coop/weapons/p_spas12.mdl
models/sence/mistake_coop/weapons/rpgrocket.mdl
models/sence/mistake_coop/weapons/rpk_shell.mdl
models/sence/mistake_coop/weapons/shell.mdl
models/sence/mistake_coop/weapons/spas12_shell.mdl
models/sence/mistake_coop/weapons/v_aps.mdl
models/sence/mistake_coop/weapons/v_crowbar.mdl
models/sence/mistake_coop/weapons/v_spas12.mdl
models/sence/mistake_coop/weapons/val_shell.mdl
models/sence/mistake_coop/weapons/w_aps.mdl
models/sence/mistake_coop/weapons/w_crowbar.mdl
models/sence/mistake_coop/weapons/w_spas12.mdl
models/sence/mistake_coop/weapons/w_spas12_ammo.mdl
models/sence/mistake_coop/zombie_slow.mdl
sound/sence/mistake_coop/bullchicken/bc_acid1.ogg
sound/sence/mistake_coop/bullchicken/bc_acid2.ogg
sound/sence/mistake_coop/bullchicken/bc_attack1.ogg
sound/sence/mistake_coop/bullchicken/bc_attack2.ogg
sound/sence/mistake_coop/bullchicken/bc_attack3.ogg
sound/sence/mistake_coop/bullchicken/bc_attackgrowl.ogg
sound/sence/mistake_coop/bullchicken/bc_attackgrowl2.ogg
sound/sence/mistake_coop/bullchicken/bc_attackgrowl3.ogg
sound/sence/mistake_coop/bullchicken/bc_bite1.ogg
sound/sence/mistake_coop/bullchicken/bc_bite2.ogg
sound/sence/mistake_coop/bullchicken/bc_bite3.ogg
sound/sence/mistake_coop/bullchicken/bc_die1.ogg
sound/sence/mistake_coop/bullchicken/bc_die2.ogg
sound/sence/mistake_coop/bullchicken/bc_die3.ogg
sound/sence/mistake_coop/bullchicken/bc_idle1.ogg
sound/sence/mistake_coop/bullchicken/bc_idle2.ogg
sound/sence/mistake_coop/bullchicken/bc_idle3.ogg
sound/sence/mistake_coop/bullchicken/bc_idle4.ogg
sound/sence/mistake_coop/bullchicken/bc_idle5.ogg
sound/sence/mistake_coop/bullchicken/bc_pain1.ogg
sound/sence/mistake_coop/bullchicken/bc_pain2.ogg
sound/sence/mistake_coop/bullchicken/bc_pain3.ogg
sound/sence/mistake_coop/bullchicken/bc_pain4.ogg
sound/sence/mistake_coop/bullchicken/bc_spithit1.ogg
sound/sence/mistake_coop/bullchicken/bc_spithit2.ogg
sound/sence/mistake_coop/bullchicken/bc_spithit3.ogg
sound/sence/mistake_coop/buttons/button10.ogg
sound/sence/mistake_coop/buttons/button8.ogg
sound/sence/mistake_coop/buttons/latchlocked1.ogg
sound/sence/mistake_coop/buttons/latchlocked2.ogg
sound/sence/mistake_coop/buttons/latchunlocked1.ogg
sound/sence/mistake_coop/buttons/latchunlocked2.ogg
sound/sence/mistake_coop/common/bodydrop1.ogg
sound/sence/mistake_coop/common/bodydrop2.ogg
sound/sence/mistake_coop/common/bodydrop3.ogg
sound/sence/mistake_coop/common/bodydrop4.ogg
sound/sence/mistake_coop/common/bodysplat.ogg
sound/sence/mistake_coop/common/npc_step1.ogg
sound/sence/mistake_coop/common/npc_step2.ogg
sound/sence/mistake_coop/common/npc_step3.ogg
sound/sence/mistake_coop/common/npc_step4.ogg
sound/sence/mistake_coop/common/wpn_denyselect.ogg
sound/sence/mistake_coop/common/wpn_hudoff.ogg
sound/sence/mistake_coop/common/wpn_hudon.ogg
sound/sence/mistake_coop/common/wpn_moveselect.ogg
sound/sence/mistake_coop/common/wpn_select.ogg
sound/sence/mistake_coop/debris/bustglass1.ogg
sound/sence/mistake_coop/debris/bustglass2.ogg
sound/sence/mistake_coop/debris/bustglass3.ogg
sound/sence/mistake_coop/debris/bustmetal1.ogg
sound/sence/mistake_coop/debris/bustmetal2.ogg
sound/sence/mistake_coop/debris/metal1.ogg
sound/sence/mistake_coop/debris/metal2.ogg
sound/sence/mistake_coop/debris/metal3.ogg
sound/sence/mistake_coop/debris/metal4.ogg
sound/sence/mistake_coop/doors/doormove10.ogg
sound/sence/mistake_coop/doors/doormove4.ogg
sound/sence/mistake_coop/doors/doormove6.ogg
sound/sence/mistake_coop/doors/doormove7.ogg
sound/sence/mistake_coop/doors/doormove8.ogg
sound/sence/mistake_coop/doors/doormove9.ogg
sound/sence/mistake_coop/doors/doorstop1.ogg
sound/sence/mistake_coop/doors/doorstop3.ogg
sound/sence/mistake_coop/doors/doorstop4.ogg
sound/sence/mistake_coop/doors/doorstop6.ogg
sound/sence/mistake_coop/dung.ogg
sound/sence/mistake_coop/fosas.ogg
sound/sence/mistake_coop/headcrab/hc_alert1.ogg
sound/sence/mistake_coop/headcrab/hc_alert2.ogg
sound/sence/mistake_coop/headcrab/hc_attack1.ogg
sound/sence/mistake_coop/headcrab/hc_attack2.ogg
sound/sence/mistake_coop/headcrab/hc_attack3.ogg
sound/sence/mistake_coop/headcrab/hc_die1.ogg
sound/sence/mistake_coop/headcrab/hc_die2.ogg
sound/sence/mistake_coop/headcrab/hc_headbite.ogg
sound/sence/mistake_coop/headcrab/hc_idle1.ogg
sound/sence/mistake_coop/headcrab/hc_idle2.ogg
sound/sence/mistake_coop/headcrab/hc_idle3.ogg
sound/sence/mistake_coop/headcrab/hc_idle4.ogg
sound/sence/mistake_coop/headcrab/hc_idle5.ogg
sound/sence/mistake_coop/headcrab/hc_pain1.ogg
sound/sence/mistake_coop/headcrab/hc_pain2.ogg
sound/sence/mistake_coop/headcrab/hc_pain3.ogg
sound/sence/mistake_coop/interf.ogg
sound/sence/mistake_coop/items/9mmclip1.ogg
sound/sence/mistake_coop/items/9mmclip2.ogg
sound/sence/mistake_coop/items/ammopickup1.ogg
sound/sence/mistake_coop/items/ammopickup2.ogg
sound/sence/mistake_coop/items/flashlight11.ogg
sound/sence/mistake_coop/items/gunpickup1.ogg
sound/sence/mistake_coop/items/gunpickup2.ogg
sound/sence/mistake_coop/items/gunpickup3.ogg
sound/sence/mistake_coop/items/gunpickup4.ogg
sound/sence/mistake_coop/items/smallmedkit1.ogg
sound/sence/mistake_coop/items/smallmedkit2.ogg
sound/sence/mistake_coop/items/weapondrop.ogg
sound/sence/mistake_coop/kulcs2.ogg
sound/sence/mistake_coop/leesik2.ogg
sound/sence/mistake_coop/music/music11.ogg
sound/sence/mistake_coop/music/music4.ogg
sound/sence/mistake_coop/player/pl_asf1.ogg
sound/sence/mistake_coop/player/pl_asf2.ogg
sound/sence/mistake_coop/player/pl_asf3.ogg
sound/sence/mistake_coop/player/pl_asf4.ogg
sound/sence/mistake_coop/player/pl_beton1.ogg
sound/sence/mistake_coop/player/pl_beton2.ogg
sound/sence/mistake_coop/player/pl_beton3.ogg
sound/sence/mistake_coop/player/pl_beton4.ogg
sound/sence/mistake_coop/player/pl_dirt1.ogg
sound/sence/mistake_coop/player/pl_dirt2.ogg
sound/sence/mistake_coop/player/pl_dirt3.ogg
sound/sence/mistake_coop/player/pl_dirt4.ogg
sound/sence/mistake_coop/player/pl_duct1.ogg
sound/sence/mistake_coop/player/pl_duct2.ogg
sound/sence/mistake_coop/player/pl_duct3.ogg
sound/sence/mistake_coop/player/pl_duct4.ogg
sound/sence/mistake_coop/player/pl_fallpain1.ogg
sound/sence/mistake_coop/player/pl_fallpain2.ogg
sound/sence/mistake_coop/player/pl_fallpain3.ogg
sound/sence/mistake_coop/player/pl_grass1.ogg
sound/sence/mistake_coop/player/pl_grass2.ogg
sound/sence/mistake_coop/player/pl_grass3.ogg
sound/sence/mistake_coop/player/pl_grass4.ogg
sound/sence/mistake_coop/player/pl_jump1.ogg
sound/sence/mistake_coop/player/pl_jump2.ogg
sound/sence/mistake_coop/player/pl_jumpland2.ogg
sound/sence/mistake_coop/player/pl_ladder1.ogg
sound/sence/mistake_coop/player/pl_ladder2.ogg
sound/sence/mistake_coop/player/pl_ladder3.ogg
sound/sence/mistake_coop/player/pl_ladder4.ogg
sound/sence/mistake_coop/player/pl_metal1.ogg
sound/sence/mistake_coop/player/pl_metal2.ogg
sound/sence/mistake_coop/player/pl_metal3.ogg
sound/sence/mistake_coop/player/pl_metal4.ogg
sound/sence/mistake_coop/player/pl_pain2.ogg
sound/sence/mistake_coop/player/pl_pain4.ogg
sound/sence/mistake_coop/player/pl_pain5.ogg
sound/sence/mistake_coop/player/pl_pain6.ogg
sound/sence/mistake_coop/player/pl_pain7.ogg
sound/sence/mistake_coop/player/pl_shell1.ogg
sound/sence/mistake_coop/player/pl_shell2.ogg
sound/sence/mistake_coop/player/pl_shell3.ogg
sound/sence/mistake_coop/player/pl_slosh1.ogg
sound/sence/mistake_coop/player/pl_slosh2.ogg
sound/sence/mistake_coop/player/pl_slosh3.ogg
sound/sence/mistake_coop/player/pl_slosh4.ogg
sound/sence/mistake_coop/player/pl_step1.ogg
sound/sence/mistake_coop/player/pl_step2.ogg
sound/sence/mistake_coop/player/pl_step3.ogg
sound/sence/mistake_coop/player/pl_step4.ogg
sound/sence/mistake_coop/player/pl_wood1.ogg
sound/sence/mistake_coop/player/pl_wood2.ogg
sound/sence/mistake_coop/player/pl_wood3.ogg
sound/sence/mistake_coop/player/pl_wood4.ogg
sound/sence/mistake_coop/roach/rch_die.ogg
sound/sence/mistake_coop/roach/rch_smash.ogg
sound/sence/mistake_coop/roach/rch_walk.ogg
sound/sence/mistake_coop/unlock.ogg
sound/sence/mistake_coop/vigyorog1.ogg
sound/sence/mistake_coop/vigyorog2.ogg
sound/sence/mistake_coop/weapons/cbar_hit1.ogg
sound/sence/mistake_coop/weapons/cbar_hit2.ogg
sound/sence/mistake_coop/weapons/cbar_hitbod1.ogg
sound/sence/mistake_coop/weapons/cbar_hitbod2.ogg
sound/sence/mistake_coop/weapons/cbar_hitbod3.ogg
sound/sence/mistake_coop/weapons/cbar_miss1.ogg
sound/sence/mistake_coop/weapons/glock_fire.ogg
sound/sence/mistake_coop/weapons/ric1.ogg
sound/sence/mistake_coop/weapons/ric2.ogg
sound/sence/mistake_coop/weapons/ric3.ogg
sound/sence/mistake_coop/weapons/ric4.ogg
sound/sence/mistake_coop/weapons/ric5.ogg
sound/sence/mistake_coop/weapons/spas12-1.ogg
sound/sence/mistake_coop/weapons/spas12-2.ogg
sound/sence/mistake_coop/weapons/spas12_insertshell.ogg
sound/sence/mistake_coop/weapons/spas12_pump.ogg
sound/sence/mistake_coop/weapons/sshell1.ogg
sound/sence/mistake_coop/weapons/sshell2.ogg
sound/sence/mistake_coop/weapons/sshell3.ogg
sound/sence/mistake_coop/zombie/claw_miss1.ogg
sound/sence/mistake_coop/zombie/claw_miss2.ogg
sound/sence/mistake_coop/zombie/claw_strike1.ogg
sound/sence/mistake_coop/zombie/claw_strike2.ogg
sound/sence/mistake_coop/zombie/claw_strike3.ogg
sound/sence/mistake_coop/zombie/pl_wood_scr1.wav
sound/sence/mistake_coop/zombie/pl_wood_scr2.wav
sound/sence/mistake_coop/zombie/pl_wood_scr3.wav
sound/sence/mistake_coop/zombie/pl_wood_scr4.wav
sound/sence/mistake_coop/zombie/zo_alert10.ogg
sound/sence/mistake_coop/zombie/zo_alert20.ogg
sound/sence/mistake_coop/zombie/zo_alert30.ogg
sound/sence/mistake_coop/zombie/zo_attack1.ogg
sound/sence/mistake_coop/zombie/zo_attack2.ogg
sound/sence/mistake_coop/zombie/zo_idle1.ogg
sound/sence/mistake_coop/zombie/zo_idle2.ogg
sound/sence/mistake_coop/zombie/zo_idle3.ogg
sound/sence/mistake_coop/zombie/zo_idle4.ogg
sound/sence/mistake_coop/zombie/zo_pain1.ogg
sound/sence/mistake_coop/zombie/zo_pain2.ogg
sprites/sence/mistake_coop/forgive.spr
sprites/sence/mistake_coop/muzzleflash1.spr
sprites/sence/mistake_coop/tukorkep.spr
