// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/metro_nitebk.tga
gfx/env/metro_nitedn.tga
gfx/env/metro_niteft.tga
gfx/env/metro_nitelf.tga
gfx/env/metro_nitert.tga
gfx/env/metro_niteup.tga
gfx/env/space_01bk.tga
gfx/env/space_01dn.tga
gfx/env/space_01ft.tga
gfx/env/space_01lf.tga
gfx/env/space_01rt.tga
gfx/env/space_01up.tga
models/chan_space_escape/cc_couch_01.mdl
models/chan_space_escape/earth.mdl
models/chan_space_escape/hera_logo.mdl
models/chan_space_escape/items/new_arm_lab.mdl
models/chan_space_escape/items/new_battery.mdl
models/chan_space_escape/items/new_cc.mdl
models/chan_space_escape/items/new_info.mdl
models/chan_space_escape/items/new_k_card.mdl
models/chan_space_escape/items/new_obs.mdl
models/chan_space_escape/items/new_phase.mdl
models/chan_space_escape/items/new_proto.mdl
models/chan_space_escape/items/new_res.mdl
models/chan_space_escape/items/new_toolbox.mdl
models/chan_space_escape/items/new_turret.mdl
models/chan_space_escape/items/w_ammo.mdl
models/chan_space_escape/items/w_health.mdl
models/chan_space_escape/items/w_heavy.mdl
models/chan_space_escape/snowmount.mdl
models/chan_space_escape/speaker2.mdl
models/chan_space_escape/table.mdl
models/ns/v_medkit.mdl
models/ns/w_siege.mdl
models/player/ns_heavy/ns_heavy.mdl
sound/chan_space/ambience/alarmloop.wav
sound/chan_space/ambience/atmospheric.mp3
sound/chan_space/ambience/b2.mp3
sound/chan_space/ambience/b3.wav
sound/chan_space/ambience/b5.wav
sound/chan_space/ambience/bastturbine.wav
sound/chan_space/ambience/bastwind2.wav
sound/chan_space/ambience/be.wav
sound/chan_space/ambience/bf.wav
sound/chan_space/ambience/bg.wav
sound/chan_space/ambience/controlroom.mp3
sound/chan_space/ambience/echodrops.mp3
sound/chan_space/ambience/emdrill.wav
sound/chan_space/ambience/eng.wav
sound/chan_space/ambience/engagelev.wav
sound/chan_space/ambience/enginethrob.mp3
sound/chan_space/ambience/hive_ambient.wav
sound/chan_space/ambience/klaxon.wav
sound/chan_space/ambience/klaxon2.wav
sound/chan_space/ambience/klaxon4.wav
sound/chan_space/ambience/lkburner2.wav
sound/chan_space/ambience/lkburner3.wav
sound/chan_space/ambience/lowsteam.wav
sound/chan_space/ambience/metalstress.wav
sound/chan_space/ambience/processing.wav
sound/chan_space/ambience/pulsingwhine.wav
sound/chan_space/ambience/rumblewhine.wav
sound/chan_space/ambience/shaft.wav
sound/chan_space/ambience/steamburst1.wav
sound/chan_space/ambience/steamburst4.wav
sound/chan_space/ammo.wav
sound/chan_space/buttons/button2.wav
sound/chan_space/buttons/button5.wav
sound/chan_space/buttons/button7.wav
sound/chan_space/buttons/button9.wav
sound/chan_space/countdown.wav
sound/chan_space/doors/doormove1.wav
sound/chan_space/doors/doormove2.wav
sound/chan_space/doors/doormove3.wav
sound/chan_space/doors/doormove4.wav
sound/chan_space/doors/doormove5.wav
sound/chan_space/doors/doormove7.wav
sound/chan_space/doors/doormove8.wav
sound/chan_space/doors/doorstop1.wav
sound/chan_space/doors/doorstop2.wav
sound/chan_space/doors/doorstop3.wav
sound/chan_space/doors/doorstop4.wav
sound/chan_space/explodingship.wav
sound/chan_space/fans/fan2.wav
sound/chan_space/gamestart1.wav
sound/chan_space/goodend.wav
sound/chan_space/main_loop.wav
sound/chan_space/medic.wav
sound/chan_space/misc/b_marine_deploy.wav
sound/chan_space/misc/ship_jets.wav
sound/chan_space/p_loop.wav
sound/chan_space/rackmove1.wav
sound/chan_space/s_loop.wav
sound/chan_space/tension.mp3
sound/chan_space/tock.mp3
sprites/chan_space/ayumiglow2.spr
sprites/chan_space/ballsmoke.spr
sprites/chan_space/blueflare2.spr
sprites/chan_space/flare3metal.spr
sprites/chan_space/haze.spr
sprites/chan_space/items/batrv2.spr
sprites/chan_space/items/k10.spr
sprites/chan_space/items/k11.spr
sprites/chan_space/items/k12.spr
sprites/chan_space/items/k13.spr
sprites/chan_space/items/k14.spr
sprites/chan_space/items/k15.spr
sprites/chan_space/items/k16.spr
sprites/chan_space/items/k2.spr
sprites/chan_space/items/k3.spr
sprites/chan_space/items/k4.spr
sprites/chan_space/items/k5.spr
sprites/chan_space/items/k6.spr
sprites/chan_space/items/k7.spr
sprites/chan_space/items/k8.spr
sprites/chan_space/items/k9.spr
sprites/chan_space/items/n1.spr
sprites/chan_space/items/n10.spr
sprites/chan_space/items/n11.spr
sprites/chan_space/items/n12.spr
sprites/chan_space/items/n13.spr
sprites/chan_space/items/n14.spr
sprites/chan_space/items/n15.spr
sprites/chan_space/items/n16.spr
sprites/chan_space/items/n2.spr
sprites/chan_space/items/n3.spr
sprites/chan_space/items/n4.spr
sprites/chan_space/items/n5.spr
sprites/chan_space/items/n6.spr
sprites/chan_space/items/n7.spr
sprites/chan_space/items/n8.spr
sprites/chan_space/items/n9.spr
sprites/chan_space/items/siege.spr
sprites/chan_space/items/welder.spr
sprites/chan_space/lobby/goal2.spr
sprites/chan_space/lobby/lobby_3.spr
sprites/chan_space/lobby/lobby_4.spr
sprites/chan_space/lobby/lobbyhelp.spr
sprites/chan_space/lobby/lobbyhelp3.spr
sprites/chan_space/lobby/logo_w1.spr
sprites/chan_space/lobby/logo_w2.spr
sprites/chan_space/lobby/logo_w3.spr
sprites/chan_space/lobby/sign_w1.spr
sprites/chan_space/lobby/sign_w2.spr
sprites/chan_space/lobby/sign_w3.spr
sprites/chan_space/moths.spr
sprites/chan_space/orflare3.spr
sprites/chan_space/redflare2.spr
sprites/chan_space/rjet1.spr
sprites/chan_space/wdrip2.spr
sprites/chan_space/weld_h.spr
sprites/chan_space/xsmoke1.spr
sprites/ns/weapon_ns_grenade.txt
sprites/ns/weapon_ns_grenadegun.txt
sprites/ns/weapon_ns_heavymachinegun.txt
sprites/ns/weapon_ns_knife.txt
sprites/ns/weapon_ns_machinegun.txt
sprites/ns/weapon_ns_mine.txt
sprites/ns/weapon_ns_pistol.txt
sprites/ns/weapon_ns_shotgun.txt
sprites/ns/weapon_ns_welder.txt
sprites/ns/weapon_siege.txt
sprites/sentry/weapon_sentry.txt
