// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_m41a.txt
models/amckern/avp10-guns/oicw/p_9mmar.mdl
models/amckern/avp10-guns/oicw/v_9mmar.mdl
models/amckern/avp10-guns/oicw/w_9mmar.mdl
models/amckern/avp10-guns/pistol/p_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/v_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/w_9mmhandgun.mdl
models/amckern/newguns/p_m16.mdl
models/amckern/newguns/shell.mdl
models/amckern/newguns/v_m16a2.mdl
models/amckern/newguns/w_m16.mdl
models/amckern/newguns/w_m16_ammo.mdl
models/amckern/p_357.mdl
models/amckern/v_357.mdl
models/amckern/w_357.mdl
models/snd/hgrunt_desert.mdl
sound/amckern/avp10-guns/sentry/fire2.wav
sound/amckern/break_wood_box_01.wav
sound/amckern/distantbattle.wav
sound/amckern/newsounds/predator/predator_shoot.ogg
sound/amckern/sc_avp8.wav
sound/amckern/tv_add1.wav
sound/amckern/tv_add2.wav
sound/amckern/tv_add3.wav
sound/amckern/tv_add4.wav
sound/amckern/tv_add5.wav
sound/amckern/tv_add6.wav
sound/amckern/tv_add7.wav
sound/amckern/tv_add8.wav
sound/amckern/tv_add_end.wav
sound/weapons/g17/magin.wav
sound/weapons/g17/magout.wav
sound/weapons/g17/slide_rel.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/drah.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/mp7/mp7_clipin.wav
sound/weapons/mp7/mp7_clipout.wav
sound/weapons/mp7/mp7_deploy.wav
sound/weapons/oicw/aug-1.wav
sound/weapons/trigun/629_shells_land.wav
sound/weapons/trigun/deagle-1.wav
sound/weapons/trigun/revolvers_bulletsin.wav
sound/weapons/trigun/revolvers_rod.wav
sound/weapons/trigun/revolvers_wheelin.wav
sound/weapons/trigun/revolvers_wheelout.wav
