// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_m41a.txt
models/amckern/avp10-guns/oicw/p_9mmar.mdl
models/amckern/avp10-guns/oicw/v_9mmar.mdl
models/amckern/avp10-guns/oicw/w_9mmar.mdl
models/amckern/avp10-guns/pistol/p_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/v_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/w_9mmhandgun.mdl
models/amckern/dr_feal_good.mdl
models/amckern/mini_zombie_barney.mdl
models/amckern/mini_zombie_soldier.mdl
models/amckern/newguns/p_m16.mdl
models/amckern/newguns/shell.mdl
models/amckern/newguns/v_m16a2.mdl
models/amckern/newguns/w_m16.mdl
models/amckern/newguns/w_m16_ammo.mdl
models/amckern/newnpcs/predator.mdl
models/amckern/p_357.mdl
models/amckern/plant_pod2.mdl
models/amckern/v_357.mdl
models/amckern/w_357.mdl
models/hezus/mt32.mdl
models/snd/hgrunt_desert.mdl
sound/amckern/avp10-guns/sentry/fire2.wav
sound/amckern/b6.wav
sound/amckern/break_wood_box_01.wav
sound/amckern/newsounds/drfeelgood.ogg
sound/amckern/newsounds/predator/predator.ogg
sound/amckern/newsounds/predator/predator2.ogg
sound/amckern/newsounds/predator/predator3.ogg
sound/amckern/newsounds/predator/predator_cloak.ogg
sound/amckern/newsounds/predator/predator_mortar.ogg
sound/amckern/newsounds/predator/predator_roar.ogg
sound/amckern/newsounds/predator/predator_search.ogg
sound/amckern/newsounds/predator/predator_search2.ogg
sound/amckern/newsounds/predator/predator_search3.ogg
sound/amckern/newsounds/predator/predator_shoot.ogg
sound/amckern/newsounds/predator/predatorbomb.ogg
sound/amckern/newsounds/predator_music.ogg
sound/amckern/sc_avp8_ambince.wav
sound/amckern/sc_avp8_radio.wav
sound/amckern/sc_avp8_radio2.wav
sound/amckern/sc_avp9_train_idle.wav
sound/amckern/sc_avp9_train_idle2.wav
sound/amckern/sc_avp9_train_idle3.wav
sound/amckern/thunder1.wav
sound/weapons/g17/magin.wav
sound/weapons/g17/magout.wav
sound/weapons/g17/slide_rel.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/drah.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/mp7/mp7_clipin.wav
sound/weapons/mp7/mp7_clipout.wav
sound/weapons/mp7/mp7_deploy.wav
sound/weapons/oicw/aug-1.wav
sound/weapons/trigun/629_shells_land.wav
sound/weapons/trigun/deagle-1.wav
sound/weapons/trigun/revolvers_bulletsin.wav
sound/weapons/trigun/revolvers_rod.wav
sound/weapons/trigun/revolvers_wheelin.wav
sound/weapons/trigun/revolvers_wheelout.wav
