// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_m41a.txt
models/amckern/avp10-guns/oicw/p_9mmar.mdl
models/amckern/avp10-guns/oicw/v_9mmar.mdl
models/amckern/avp10-guns/oicw/w_9mmar.mdl
models/amckern/avp10-guns/pistol/p_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/v_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/w_9mmhandgun.mdl
models/amckern/bigbluetruck.mdl
models/amckern/garg33.mdl
models/amckern/hgrunt.mdl
models/amckern/newguns/p_m16.mdl
models/amckern/newguns/shell.mdl
models/amckern/newguns/v_m16a2.mdl
models/amckern/newguns/w_m16.mdl
models/amckern/newguns/w_m16_ammo.mdl
models/amckern/ourano.mdl
models/amckern/p_357.mdl
models/amckern/robobug2.mdl
models/amckern/rubbish.mdl
models/amckern/scientist.mdl
models/amckern/v_357.mdl
models/amckern/w_357.mdl
models/amckern/woodgibs.mdl
models/snd/hgrunt_desert.mdl
sound/amckern/avp10-guns/sentry/fire2.wav
sound/amckern/break_wood_box_01.wav
sound/amckern/car1.wav
sound/amckern/cicada3.wav
sound/amckern/door_slide.wav
sound/amckern/intro.wav
sound/amckern/lift_hum_loop.wav
sound/amckern/newsounds/dinocrisis.ogg
sound/amckern/newsounds/introgleum.ogg
sound/amckern/newsounds/predator/predator_shoot.ogg
sound/amckern/police_alert_01.wav
sound/amckern/police_alert_08.wav
sound/amckern/police_alert_09.wav
sound/amckern/police_noise_04.wav
sound/amckern/regroup.wav
sound/amckern/security_access_denied.wav
sound/amckern/security_access_granted.wav
sound/amckern/sub_hiss.wav
sound/amckern/target_found.wav
sound/amckern/terimante.wav
sound/amckern/truck.wav
sound/amckern/what_body.ogg
sound/gscientist/scientist_diebackwards.wav
sound/gscientist/scientist_dieforwards.wav
sound/gscientist/scientist_dieheadshot.wav
sound/gscientist/scientist_diesimple.wav
sound/gscientist/scientist_dieviolent.wav
sound/ourano/Ourano_BigFlinch_F0.wav
sound/ourano/Ourano_Bite_F0.wav
sound/ourano/Ourano_Chew_F0.wav
sound/ourano/Ourano_DieSimple_F0.wav
sound/ourano/Ourano_FootStep1.wav
sound/ourano/Ourano_FootStep2.wav
sound/ourano/Ourano_MoveAttack_Vocals.wav
sound/ourano/Ourano_QuickAttack_F0.wav
sound/ourano/Ourano_Roar_F0.wav
sound/ourano/ourano_SmallFlinch_F0.wav
sound/weapons/g17/magin.wav
sound/weapons/g17/magout.wav
sound/weapons/g17/slide_rel.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/drah.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/mp7/mp7_clipin.wav
sound/weapons/mp7/mp7_clipout.wav
sound/weapons/mp7/mp7_deploy.wav
sound/weapons/oicw/aug-1.wav
sound/weapons/trigun/629_shells_land.wav
sound/weapons/trigun/deagle-1.wav
sound/weapons/trigun/revolvers_bulletsin.wav
sound/weapons/trigun/revolvers_rod.wav
sound/weapons/trigun/revolvers_wheelin.wav
sound/weapons/trigun/revolvers_wheelout.wav
