// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_m41a.txt
models/amckern/alien.mdl
models/amckern/avp10-guns/oicw/p_9mmar.mdl
models/amckern/avp10-guns/oicw/v_9mmar.mdl
models/amckern/avp10-guns/oicw/w_9mmar.mdl
models/amckern/avp10-guns/pistol/p_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/v_9mmhandgun.mdl
models/amckern/avp10-guns/pistol/w_9mmhandgun.mdl
models/amckern/newguns/p_m16.mdl
models/amckern/newguns/shell.mdl
models/amckern/newguns/v_m16a2.mdl
models/amckern/newguns/w_m16.mdl
models/amckern/newguns/w_m16_ammo.mdl
models/amckern/newnpcs/alien_bs.mdl
models/amckern/newnpcs/alien_gonome.mdl
models/amckern/newnpcs/alien_praetorian.mdl
models/amckern/newnpcs/alien_q.mdl
models/amckern/newnpcs/facehugger.mdl
models/amckern/newnpcs/sentry.mdl
models/amckern/p_357.mdl
models/amckern/v_357.mdl
models/amckern/w_357.mdl
sound/amckern/avp10-amb1.wav
sound/amckern/avp10-amb2.wav
sound/amckern/avp10-amb3.wav
sound/amckern/avp10-amb4.wav
sound/amckern/avp10-amb5.wav
sound/amckern/avp10-computer.wav
sound/amckern/avp10-guns/alien/chestburst.wav
sound/amckern/avp10-guns/alien/hit.wav
sound/amckern/avp10-guns/alien/teeth.wav
sound/amckern/avp10-guns/sentry/fire1.wav
sound/amckern/avp10-guns/sentry/fire2.wav
sound/amckern/avp10-guns/sentry/fire3.wav
sound/amckern/b6.wav
sound/amckern/cavern_alien_ambience.wav
sound/amckern/klaxon2.wav
sound/amckern/teleport_rift.wav
sound/weapons/g17/magin.wav
sound/weapons/g17/magout.wav
sound/weapons/g17/slide_rel.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/drah.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/oicw/aug-1.wav
sound/weapons/oicw/glaunchready.wav
sound/weapons/oicw/oicw_clipin.wav
sound/weapons/oicw/oicw_clipout.wav
sound/weapons/oicw/oicw_deploy.wav
sound/weapons/trigun/629_shells_land.wav
sound/weapons/trigun/deagle-1.wav
sound/weapons/trigun/revolvers_bulletsin.wav
sound/weapons/trigun/revolvers_rod.wav
sound/weapons/trigun/revolvers_wheelin.wav
sound/weapons/trigun/revolvers_wheelout.wav
