// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/d1e3skybk.tga
gfx/env/d1e3skydn.tga
gfx/env/d1e3skyft.tga
gfx/env/d1e3skylf.tga
gfx/env/d1e3skyrt.tga
gfx/env/d1e3skyup.tga
hellmouth.wad
models/custom_monsters/pitdrone/helldrone.mdl
models/hellmouth/agrunt.mdl
models/hellmouth/angelchubstat_HUGE.mdl
models/hellmouth/big_mom.mdl
models/hellmouth/controller.mdl
models/hellmouth/gonome.mdl
models/hellmouth/headcrab.mdl
models/hellmouth/hgruntdead.mdl
models/hellmouth/panther.mdl
models/hellmouth/puppeh.mdl
models/hellmouth/slavehell.mdl
models/hellmouth/tentacle.mdl
models/hellmouth/zombie.mdl
models/hellmouth/zombie_barney.mdl
models/hellmouth/zombie_soldier.mdl
sound/hellmouth/spawn.wav
sound/hellmouth/spawn2.wav
sound/panther/p_alert1.wav
sound/panther/p_alert2.wav
sound/panther/p_alert3.wav
sound/panther/p_die1.wav
sound/panther/p_die2.wav
sound/panther/p_idle1.wav
sound/panther/p_idle2.wav
sound/panther/p_idle3.wav
sound/panther/p_pain1.wav
sound/panther/p_pain2.wav
sound/panther/p_zap1.wav
sound/panther/p_zap2.wav
sound/panther/pclaw_miss1.wav
sound/panther/pclaw_miss2.wav
sound/panther/pclaw_strike1.wav
sound/panther/pclaw_strike2.wav
sound/panther/pclaw_strike3.wav
